In [40]:
import pandas as pd

df = pd.read_csv("Data/matches.csv")

In [41]:
df.sample(1)

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,...,match_winner,wb_runs,wb_wickets,balls_left,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure,super_over_match
9,10,"April 05, 2026","Rajiv Gandhi International Stadium, Hyderabad",SRH,LSG,League,LSG,Bowl,156.0,9.0,...,LSG,NaN,5.0,1.0,Mohammed Shami,Rishabh Pant,68.0,Mohammed Shami,2--9,No

In [45]:
df.isnull().sum()

match_id                0
date                    0
venue                   0
team1                   0
team2                   0
stage                   0
toss_winner             0
toss_decision           0
first_ings_score        1
first_ings_wkts         1
second_ings_score       1
second_ings_wkts        1
match_result            0
match_winner            1
wb_runs                24
wb_wickets             17
balls_left              1
player_of_the_match     1
top_scorer              1
highscore               1
best_bowling            1
best_bowling_figure     1
super_over_match        0
dtype: int64

In [44]:
df.isnull().sum()/ len(df) * 100

match_id                0.000000
date                    0.000000
venue                   0.000000
team1                   0.000000
team2                   0.000000
stage                   0.000000
toss_winner             0.000000
toss_decision           0.000000
first_ings_score        2.564103
first_ings_wkts         2.564103
second_ings_score       2.564103
second_ings_wkts        2.564103
match_result            0.000000
match_winner            2.564103
wb_runs                61.538462
wb_wickets             43.589744
balls_left              2.564103
player_of_the_match     2.564103
top_scorer              2.564103
highscore               2.564103
best_bowling            2.564103
best_bowling_figure     2.564103
super_over_match        0.000000
dtype: float64

In [ ]:
df["team1"].unique()

<StringArray>
['RCB', 'MI', 'RR', 'PBKS', 'LSG', 'KKR', 'CSK', 'DC', 'GT', 'SRH']
Length: 10, dtype: str

In [48]:
df["team1"].unique()
rcb=df["team1"]=="RCB"
df[rcb]

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,...,match_winner,wb_runs,wb_wickets,balls_left,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure,super_over_match
0,1,"March 28, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,SRH,League,RCB,Bowl,201.0,9.0,...,RCB,NaN,6.0,26.0,Jacob Duffy,Ishan Kishan,80.0,Jacob Duffy,3--22,No
10,11,"April 05, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,CSK,League,CSK,Bowl,250.0,3.0,...,RCB,43.0,NaN,2.0,Tim David,Tim David,70.0,Bhuvneshwar Kumar,3--41,No
22,23,"April 15, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,LSG,League,RCB,Bowl,146.0,10.0,...,RCB,NaN,5.0,29.0,Josh Hazlewood,Virat Kohli,49.0,Rasikh Salam,4--24,No
25,26,"April 18, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,DC,League,DC,Bowl,175.0,8.0,...,DC,NaN,6.0,1.0,Tristan Stubbs,Phil Salt,63.0,Bhuvneshwar Kumar,3--26,No
33,34,"April 24, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,GT,League,RCB,Bowl,205.0,3.0,...,RCB,NaN,5.0,7.0,Virat Kohli,Sai Sudarshan,100.0,Rashid Khan,2--49,No

In [ ]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [match_id, date, venue, team1, team2, stage, toss_winner, toss_decision, first_ings_score, first_ings_wkts, second_ings_score, second_ings_wkts, match_result, match_winner, wb_runs, wb_wickets, balls_left, player_of_the_match, top_scorer, highscore, best_bowling, best_bowling_figure, super_over_match]
Index: []

[0 rows x 23 columns]

In [133]:
df.dropna(inplace=True)
df.isnull().sum()

match_id               0
date                   0
venue                  0
team1                  0
team2                  0
stage                  0
toss_winner            0
toss_decision          0
first_ings_score       0
first_ings_wkts        0
second_ings_score      0
second_ings_wkts       0
match_result           0
match_winner           0
wb_runs                0
wb_wickets             0
balls_left             0
player_of_the_match    0
top_scorer             0
highscore              0
best_bowling           0
best_bowling_figure    0
super_over_match       0
dtype: int64

In [128]:
df.columns

Index(['match_id', 'date', 'venue', 'team1', 'team2', 'stage', 'toss_winner',
       'toss_decision', 'first_ings_score', 'first_ings_wkts',
       'second_ings_score', 'second_ings_wkts', 'match_result', 'match_winner',
       'wb_runs', 'wb_wickets', 'balls_left', 'player_of_the_match',
       'top_scorer', 'highscore', 'best_bowling', 'best_bowling_figure',
       'super_over_match'],
      dtype='str')

In [129]:
df['venue'].value_counts()

Series([], Name: count, dtype: int64)

In [130]:
df['match_winner'].value_counts()

Series([], Name: count, dtype: int64)

In [131]:
df.describe()

,match_id,first_ings_score,first_ings_wkts,second_ings_score,second_ings_wkts,wb_runs,wb_wickets,balls_left,highscore
count,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [116]:
df.head()

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 0 entries
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   match_id             0 non-null      int64
 1   date                 0 non-null      str
 2   venue                0 non-null      str
 3   team1                0 non-null      str
 4   team2                0 non-null      str
 5   stage                0 non-null      str
 6   toss_winner          0 non-null      str
 7   toss_decision        0 non-null      str
 8   first_ings_score     0 non-null      float64
 9   first_ings_wkts      0 non-null      float64
 10  second_ings_score    0 non-null      float64
 11  second_ings_wkts     0 non-null      float64
 12  match_result         0 non-null      str
 13  match_winner         0 non-null      str
 14  wb_runs              0 non-null      float64
 15  wb_wickets           0 non-null      float64
 16  balls_left           0 non-null      float64
 17  player_of_the_match  0 non-null      str
 18  top_scorer           0 non-null      str
 19  highscore            0 non-null      float64
 20  best_bowling         0 non-null      str
 21  best_bowling_figure  0 non-null      str
 22  super_over_match     0 non-null      str
dtypes: float64(8), int64(1), str(14)
memory usage: 132.0 bytes