In [49]:
#ultiple Linear Regression ek Machine Learning algorithm hai jo ek dependent variable (output) ko predict karta hai do ya do se zyada independent variables (inputs) ki help se.
# ex - House predictions, Students marks
# Single LR - y=mx+c
# Multi LR - y= b0+b1x1+b2x2....b2xn
#Why?
## because it has multiple independent variable.
# y = output
# be = intercept
# b1b2b3.... = coefficients
# X1, X2, X3... = features

Practical

In [50]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
housing = fetch_california_housing()
print(type(housing))

<class 'sklearn.utils._bunch.Bunch'>

In [51]:
housing=fetch_california_housing()

In [52]:
print(type(housing))

<class 'sklearn.utils._bunch.Bunch'>

In [53]:
print(housing.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'feature_names', 'DESCR'])

In [54]:
print (housing. feature_names)

['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']

In [55]:
df = pd. DataFrame(housing.data,columns = housing. feature_names)

In [56]:
df['HousePrice']=housing.target

In [57]:
df.head(20)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,HousePrice
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
5,4.0368,52.0,4.761658,1.103627,413.0,2.139896,37.85,-122.25,2.697
6,3.6591,52.0,4.931907,0.951362,1094.0,2.128405,37.84,-122.25,2.992
7,3.1200,52.0,4.797527,1.061824,1157.0,1.788253,37.84,-122.25,2.414
8,2.0804,42.0,4.294118,1.117647,1206.0,2.026891,37.84,-122.26,2.267
9,3.6912,52.0,4.970588,0.990196,1551.0,2.172269,37.84,-122.25,2.611
10,3.2031,52.0,5.477612,1.079602,910.0,2.263682,37.85,-122.26,2.815
11,3.2705,52.0,4.772480,1.024523,1504.0,2.049046,37.85,-122.26,2.418
12,3.0750,52.0,5.322650,1.012821,1098.0,2.346154,37.85,-122.26,2.135
13,2.6736,52.0,4.000000,1.097701,345.0,1.982759,37.84,-122.26,1.913
14,1.9167,52.0,4.262903,1.009677,1212.0,1.954839,37.85,-122.26,1.592
15,2.1250,50.0,4.242424,1.071970,697.0,2.640152,37.85,-122.26,1.400
16,2.7750,52.0,5.939577,1.048338,793.0,2.395770,37.85,-122.27,1.525
17,2.1202,52.0,4.052805,0.966997,648.0,2.138614,37.85,-122.27,1.555
18,1.9911,50.0,5.343675,1.085919,990.0,2.362768,37.84,-122.26,1.587
19,2.6033,52.0,5.465455,1.083636,690.0,2.509091,37.84,-122.27,1.629

In [58]:
df.tail(20)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,HousePrice
20620,4.5625,40.0,4.125000,0.854167,151.0,3.145833,39.05,-121.48,1.000
20621,2.3661,37.0,7.923567,1.573248,484.0,3.082803,39.01,-121.47,0.775
20622,2.4167,20.0,4.808917,0.936306,457.0,2.910828,39.00,-121.44,0.670
20623,2.8235,32.0,5.101322,1.074890,598.0,2.634361,39.03,-121.37,0.655
20624,3.0739,16.0,5.835052,1.030928,731.0,2.512027,39.04,-121.41,0.872
20625,4.1250,37.0,7.285714,1.214286,29.0,2.071429,39.12,-121.52,0.720
20626,2.1667,36.0,6.573099,1.076023,504.0,2.947368,39.18,-121.43,0.938
20627,3.0000,5.0,6.067797,1.101695,169.0,2.864407,39.13,-121.32,1.625
20628,2.5952,19.0,5.238462,1.079487,1018.0,2.610256,39.10,-121.48,0.924
20629,2.0943,28.0,5.519802,1.020902,6912.0,3.801980,39.12,-121.39,1.083
20630,3.5673,11.0,5.932584,1.134831,1257.0,2.824719,39.29,-121.32,1.120
20631,3.5179,15.0,6.145833,1.141204,1200.0,2.777778,39.33,-121.40,1.072
20632,3.1250,15.0,6.023377,1.080519,1047.0,2.719481,39.26,-121.45,1.156
20633,2.5495,27.0,5.445026,1.078534,1082.0,2.832461,39.19,-121.53,0.983
20634,3.7125,28.0,6.779070,1.148256,1041.0,3.026163,39.27,-121.56,1.168
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [59]:
print(df.shape)

(20640, 9)

In [60]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
 8   HousePrice  20640 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB

In [61]:
df.info

<bound method DataFrame.info of        MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85
...       ...       ...       ...        ...         ...       ...       ...
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37

       Longitude  HousePrice
0        -122.23       4.526
1        -122.22       3.585
2        -122.24       3.521
3        -122.25       3.413
4        -122.25       3.422
...          ...         ...
20635    -121.09       0.781
20636    -121.21       0.771
20637    -121.22       0.923
20638    -121.32       0.847
20639    -121.24       0.894

[20640 rows x 9 columns]>

In [62]:
df.isnull().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
HousePrice    0
dtype: int64

In [63]:
df.duplicated().sum()

np.int64(0)

In [64]:
corr=df.corr()

In [65]:
corr

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,HousePrice
MedInc,1.000000,-0.119034,0.326895,-0.062040,0.004834,0.018766,-0.079809,-0.015176,0.688075
HouseAge,-0.119034,1.000000,-0.153277,-0.077747,-0.296244,0.013191,0.011173,-0.108197,0.105623
AveRooms,0.326895,-0.153277,1.000000,0.847621,-0.072213,-0.004852,0.106389,-0.027540,0.151948
AveBedrms,-0.062040,-0.077747,0.847621,1.000000,-0.066197,-0.006181,0.069721,0.013344,-0.046701
Population,0.004834,-0.296244,-0.072213,-0.066197,1.000000,0.069863,-0.108785,0.099773,-0.024650
AveOccup,0.018766,0.013191,-0.004852,-0.006181,0.069863,1.000000,0.002366,0.002476,-0.023737
Latitude,-0.079809,0.011173,0.106389,0.069721,-0.108785,0.002366,1.000000,-0.924664,-0.144160
Longitude,-0.015176,-0.108197,-0.027540,0.013344,0.099773,0.002476,-0.924664,1.000000,-0.045967
HousePrice,0.688075,0.105623,0.151948,-0.046701,-0.024650,-0.023737,-0.144160,-0.045967,1.000000

In [66]:
corr['HousePrice'].sort_values(ascending=False)

HousePrice    1.000000
MedInc        0.688075
AveRooms      0.151948
HouseAge      0.105623
AveOccup     -0.023737
Population   -0.024650
Longitude    -0.045967
AveBedrms    -0.046701
Latitude     -0.144160
Name: HousePrice, dtype: float64

In [67]:
x=df.drop('HousePrice',axis=1)
y=df['HousePrice']

In [68]:
print(x.columns)

Index(['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup',
       'Latitude', 'Longitude'],
      dtype='str')

In [69]:
print(y.head())

0    4.526
1    3.585
2    3.521
3    3.413
4    3.422
Name: HousePrice, dtype: float64

In [76]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=40)

In [77]:
print(x_train. shape)

(16512, 8)

In [ ]:
print(x_test.shape)

(4128, 8)

In [80]:
print (y_train. shape)

(16512,)

In [81]:
print(y_test.shape)

(4128,)

In [83]:
model = LinearRegression()
model. fit(x_train, y_train)

LinearRegression()

In [84]:
print(model.intercept_)

-36.84337456381572

In [86]:
y_pred=model.predict(x_test)

In [89]:
comparison = pd.DataFrame({
    'Actual': y_test.values,
    'Predicted': y_pred
})

comparison.head(16)

     Actual  Predicted
0   2.26500   2.004130
1   1.96200   2.575619
2   1.45800   1.197698
3   4.20000   1.689343
4   2.57800   2.187609
5   1.44100   2.138624
6   3.47400   2.820414
7   1.85400   1.626702
8   4.32100   3.145142
9   2.88200   3.016335
10  1.05100   1.830772
11  5.00001   4.925455
12  2.16900   1.883421
13  3.40400   3.316320
14  4.30200   2.913767
15  1.63100   2.099586

In [92]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MAE :", mae)
print("MSE :", mse)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE : 0.5389572480554758
MSE : 0.5417517275769406
RMSE: 0.7360378574346164
R2 Score: 0.6075794091011186

In [94]:
new_house =[[
8,20,6.5,1,1000, 3.0,34.2, -118.4
]]
prediction_new_house = model.predict (new_house)
prediction_new_house[0]

c:\Users\danny\OneDrive\Documents\coding\PBEL (Project-Based Experiential Learning) sessions\PBEL12\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

np.float64(3.6951677644476177)